# Generated by Django 6.0.1 on 2026-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
