# Generated by Django 6.0.1 on 2026-01-30 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('financeiro', '0002_contareceber_delete_despesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='data_lancamento',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('pago', 'Pago')], default='aberto', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(blank=True, max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.contareceber')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto')),
            ],
        ),
    ]
