# Generated by Django 6.0.1 on 2026-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_itemfiado_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfiado',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
